# Generated by Django 3.2.4 on 2021-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='marks',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
